# Use a Node.js base image
FROM node:22.12.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose the port for Angular development server
EXPOSE 4200

# Run Angular's development server
CMD ["npm", "run", "start"]
