# Build Stage
FROM node:22.12.0 as frontend-build
WORKDIR /frontend

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the source code
COPY . .

# Build the Angular application
RUN npm run build --prod

# Runtime Stage
FROM nginx:1.21.6
COPY --from=frontend-build /frontend/dist/frontend /usr/share/nginx/html

# Expose the port for the web server
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
