version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coursemaster-backend
    ports:
      - "8080:8080"
    networks:
      - coursemaster-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coursemaster-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app # Mount the local frontend directory
      - /app/node_modules # Exclude node_modules from the volume
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
    networks:
      - coursemaster-network
    depends_on:
      - backend

networks:
  coursemaster-network:
    driver: bridge
