# Backend Build Stage
FROM maven:3.8.7-eclipse-temurin-17 as backend-build
WORKDIR /app

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy the source code and build the application
COPY src ./src
RUN mvn package -DskipTests

# Runtime Stage
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=backend-build /app/target/*.jar app.jar

# Expose the backend port
EXPOSE 8080

# Start the backend service
ENTRYPOINT ["java", "-jar", "app.jar"]


