# Stage 1: Build the application
FROM maven:3.8.7-eclipse-temurin-17 as build
WORKDIR /app

# Copy the Maven configuration and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy the application source code
COPY src ./src

# Build the applicati
